<!-- <script src="assets/bent/js/jquery.min.js"></script> -->
<!-- <script src="assets/bent/js/bootstrap.min.js"></script> -->
<!-- <script src="assets/bent/js/owl.carousel.js"></script> -->
<!-- <script src="assets/bent/js/jquery.fitvids.js"></script> -->
<!-- <script src="assets/bent/js/smoothscroll.js"></script> -->
<!-- <script src="assets/bent/js/jquery.parallax-1.1.3.js"></script> -->
<!-- <script src="assets/bent/js/jquery.prettyPhoto.js"></script> -->
<!-- <script src="assets/bent/js/jquery.ajaxchimp.min.js"></script> -->
<!-- <script src="assets/bent/js/jquery.ajaxchimp.langs.js"></script> -->
<!-- <script src="assets/bent/js/wow.min.js"></script> -->
<!-- <script src="assets/bent/js/waypoints.min.js"></script> -->
<script src="assets/bent/js/jquery.counterup.min.js"></script>
<!-- <script src="assets/bent/js/script.js"></script> -->